import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {before,after,test} from 'node:test';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(),A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002',ADMIN='10000000-0000-4000-8000-000000000003',C='20000000-0000-4000-8000-000000000001';let review;
before(async()=>{await db.exec(await readFile('tests/security/observed-schema.sql','utf8'));await db.exec(await readFile('supabase/migrations/20260917120000_p0_content_privacy_and_permissions.sql','utf8'));await db.exec(await readFile('supabase/migrations/20260918030000_company_directory.sql','utf8'));await db.exec(await readFile('supabase/migrations/20260919010000_company_reviews.sql','utf8'));for(const [id,n,admin]of [[A,'a',false],[B,'b',false],[ADMIN,'admin',true]]){await db.query('insert into auth.users values($1)',[id]);await db.query('insert into public.profiles(id,nickname,is_admin) values($1,$2,$3)',[id,n,admin])}await db.query("insert into public.companies(id,slug,name,source_system,source_id,source_url,source_updated_on,checked_on,is_published) values($1,'review-company','Test','verified_manual','review-company','https://example.org','2026-09-18','2026-09-18',true)",[C]);});after(()=>db.close());
async function as(id,aal,fn,commit=false){await db.exec('begin');await db.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:id,aal})]);await db.exec(`set local role ${id?'authenticated':'anon'}`);try{const r=await fn();await db.exec(commit?'commit':'rollback');return r}catch(e){await db.exec('rollback');throw e}}
for(const [label,id,aal]of [['anon',null,'aal1'],['A',A,'aal1'],['B',B,'aal1'],['admin aal1',ADMIN,'aal1'],['admin aal2',ADMIN,'aal2']])for(const q of ['select * from public.company_reviews',"insert into public.company_reviews default values","update public.company_reviews set status='approved'","delete from public.company_reviews"])test(`${label}: raw review table denied ${q}`,()=>assert.rejects(as(id,aal,()=>db.exec(q)),e=>e.code==='42501'));
test('anon cannot submit',()=>assert.rejects(as(null,'aal1',()=>db.query('select public.submit_company_review($1,3,$2,$3,$4)',[C,'hello title','good '.repeat(10),'bad '.repeat(10)])),e=>e.code==='42501'));
test('A submits; DB fixes identity and pending state',async()=>{review=(await as(A,'aal1',()=>db.query('select public.submit_company_review($1,3,$2,$3,$4) id',[C,'hello title','good '.repeat(10),'bad '.repeat(10)]),true)).rows[0].id;const r=(await db.query('select * from public.company_reviews')).rows[0];assert.equal(r.user_id,A);assert.equal(r.status,'pending');assert.equal(r.access_until,null)});
test('A cannot flood or duplicate submissions',()=>assert.rejects(as(A,'aal1',()=>db.query('select public.submit_company_review($1,3,$2,$3,$4)',[C,'hello title','good '.repeat(10),'bad '.repeat(10)]))));
for(const [label,id,aal]of [['A',A,'aal2'],['B',B,'aal1'],['admin aal1',ADMIN,'aal1']])test(`${label}: moderation denied`,()=>assert.rejects(as(id,aal,()=>db.query("select public.moderate_company_review($1,'approved')",[review])),e=>e.code==='42501'));
test('B cannot see A pending review or withdraw it',async()=>{await as(B,'aal1',async()=>{assert.equal((await db.query('select * from public.my_company_reviews()')).rows.length,0);await db.query('select public.withdraw_company_review($1)',[review])},true);assert.equal((await db.query('select status from public.company_reviews')).rows[0].status,'pending')});
test('A cannot read before approval',()=>assert.rejects(as(A,'aal1',()=>db.query('select * from public.list_company_reviews($1)',[C])),e=>e.code==='42501'));
test('admin aal2 approves; grants 90 days only once',async()=>{await as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'approved')",[review]),true);assert.equal((await db.query("select access_until-approved_at=interval '90 days' valid from public.company_reviews")).rows[0].valid,true);await assert.rejects(as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'approved')",[review])))});
test('A reads approved DTO without author identity; B denied',async()=>{const r=(await as(A,'aal1',()=>db.query('select * from public.list_company_reviews($1)',[C]))).rows[0];assert.deepEqual(Object.keys(r).sort(),['id','rating','title','pros','cons','published_on'].sort());assert.ok(!JSON.stringify(r).includes(A));await assert.rejects(as(B,'aal1',()=>db.query('select * from public.list_company_reviews($1)',[C])),e=>e.code==='42501')});
test('expired access denied',async()=>{await db.exec('begin');await db.query("update public.company_reviews set access_until=now()-interval '1 second' where id=$1",[review]);await db.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:A,aal:'aal1'})]);await db.exec('set local role authenticated');await assert.rejects(db.query('select * from public.list_company_reviews($1)',[C]),e=>e.code==='42501');await db.exec('rollback')});
test('withdrawal removes access and hides content',async()=>{await as(A,'aal1',()=>db.query('select public.withdraw_company_review($1)',[review]),true);assert.equal((await as(A,'aal1',()=>db.query('select public.company_review_access() expiry'))).rows[0].expiry,null);await assert.rejects(as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'approved')",[review])))});
test('rejected or withdrawn review can be corrected after cooldown',async()=>{await db.query("update public.company_reviews set created_at=now()-interval '25 hours' where id=$1",[review]);const r=await as(A,'aal1',()=>db.query('select public.submit_company_review($1,4,$2,$3,$4) id',[C,'corrected title','good '.repeat(10),'bad '.repeat(10)]),true);assert.equal(r.rows[0].id,review);const row=(await db.query('select status,access_until from public.company_reviews where id=$1',[review])).rows[0];assert.equal(row.status,'pending');assert.equal(row.access_until,null)});
test('invalid rating and too short bodies rejected',async()=>{for(const args of [[C,6,'valid title','good '.repeat(10),'bad '.repeat(10)],[C,3,'valid title','short','short']])await assert.rejects(as(B,'aal1',()=>db.query('select public.submit_company_review($1,$2,$3,$4,$5)',args)),e=>e.code==='23514')});
test('admin cannot approve own submission',async()=>{const r=await as(ADMIN,'aal2',()=>db.query('select public.submit_company_review($1,3,$2,$3,$4) id',[C,'admin own title','good '.repeat(10),'bad '.repeat(10)]),true);await assert.rejects(as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'approved')",[r.rows[0].id])),e=>e.code==='42501')});
test('revocation removes access immediately',async()=>{await as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'approved')",[review]),true);await as(ADMIN,'aal2',()=>db.query("select public.moderate_company_review($1,'rejected')",[review]),true);assert.equal((await as(A,'aal1',()=>db.query('select public.company_review_access() expiry'))).rows[0].expiry,null)});
