"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from '@/components/Header';import Footer from '@/components/Footer';import {supabase} from '@/lib/supabase';import styles from '../company.module.css';
type Own={id:string;company_id:string;company_name:string;title:string;status:string};
export default function CompanyWritePage(){
 const [company,setCompany]=useState<{id:string;name:string}|null>(null),[user,setUser]=useState(false),[ready,setReady]=useState(false),[mine,setMine]=useState<Own[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const {data}=supabase.auth.onAuthStateChange(()=>{setMine([]);setUser(false);setReady(false);setRefresh(x=>x+1)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{let active=true;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!active)return;setUser(!!user);const id=new URLSearchParams(window.location.search).get('company');if(id){const c=await supabase.from('companies').select('id,name').eq('id',id).maybeSingle();if(active)setCompany(c.data)}if(user){const r=await supabase.rpc('my_company_reviews');if(active){setMine(r.data??[]);if(r.error)setMessage('내 리뷰를 불러오지 못했습니다.')}}if(active)setReady(true)}void load();return()=>{active=false}},[refresh]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!company)return;setBusy(true);setMessage('');const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('submit_company_review',{p_company_id:company.id,p_rating:Number(f.get('rating')),p_title:f.get('title'),p_pros:f.get('pros'),p_cons:f.get('cons')});setBusy(false);setMessage(error?'제출하지 못했습니다. 로그인 상태, 회사당 1건·24시간당 1건 제한과 입력 길이를 확인해주세요.':'접수했습니다. 승인 후 90일 열람권이 활성화됩니다.');if(!error)setRefresh(x=>x+1)}
 async function withdraw(id:string){setBusy(true);const {error}=await supabase.rpc('withdraw_company_review',{p_id:id});setBusy(false);setMessage(error?'철회하지 못했습니다.':'리뷰를 비공개로 철회했고 해당 리뷰의 열람권을 종료했습니다.');setRefresh(x=>x+1)}
 const labels:Record<string,string>={pending:'승인 대기',approved:'승인',rejected:'반려',withdrawn:'철회'};
 return <><Header/><main className={styles.main}><Link href="/company" className={styles.back}>← 회사 찾기</Link><h1>기업 리뷰 작성</h1><p className={styles.note}>직접 일한 경험만 작성해주세요. 실명·연락처·특정인을 알아볼 수 있는 내용은 적지 마세요. 승인된 리뷰는 열람권이 있는 회원에게 익명으로 표시됩니다. 회사당 1건, 하루 1건 제출할 수 있습니다.</p>{message&&<p role="status" className={styles.note}>{message}</p>}{!ready?<p>확인 중…</p>:!user?<Link className={styles.button} href="/login">로그인 후 작성</Link>:<>{company?<form className={styles.filters} onSubmit={submit}><h2>{company.name}</h2><label>전체 평점<select name="rating" defaultValue="3">{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}점</option>)}</select></label><label>한 줄 평가 (5~100자)<input name="title" required minLength={5} maxLength={100}/></label><label>장점 (30~3,000자)<textarea name="pros" required minLength={30} maxLength={3000} rows={5}/></label><label>아쉬운 점 (30~3,000자)<textarea name="cons" required minLength={30} maxLength={3000} rows={5}/></label><label><span><input type="checkbox" required style={{width:'auto'}}/> 직접 경험한 내용이며 개인정보를 포함하지 않았습니다.</span></label><button disabled={busy||mine.some(r=>r.company_id===company.id&&['pending','approved'].includes(r.status))} className={styles.button}>{busy?'처리 중…':'승인 요청'}</button><p className={styles.note}>승인 후 90일간 열람할 수 있습니다. 승인 반려·철회 시에는 해당 리뷰의 열람권이 종료됩니다.</p></form>:<p>회사 목록에서 회사를 선택한 후 리뷰를 작성해주세요.</p>}<h2>내 리뷰</h2>{mine.length===0?<p>제출한 리뷰가 없습니다.</p>:mine.map(r=><article className={styles.card} key={r.id}><h3>{r.company_name} · {r.title}</h3><p>{labels[r.status]}</p>{r.status!=='withdrawn'&&<button disabled={busy} onClick={()=>withdraw(r.id)}>리뷰 철회 · 해당 열람권 종료</button>}</article>)}</>}</main><Footer/></>
}
